### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by EslamHaourn** [SKRohit/Improving-YOLOv3#2]
Hi, 
I face this error with the lines:
Traceback (most recent call last):
  File "train.py", line 172, in <module>
    loss = model(imgs, targets)
  File "/home/eslam/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/eslam/Desktop/PyTorch-YOLOv3-kitti-master/model.py", line 294, in forward
    x, layer_loss = module[0](x, targets, img_dim)
  File "/home/eslam/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/eslam/Desktop/PyTorch-YOLOv3-kitti-master/model.py", line 188, in forward
    iou_scores, class_mask, obj_mask, noobj_mask, tx, ty, tw, th, tcls, tconf = build_targets(
  File "/home/eslam/Desktop/PyTorch-YOLOv3-kitti-master/utils/utils.py", line 469, in build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0
RuntimeError: CUDA error: device-side assert triggered

what should I do?
Thanks in advance.

**Comment by EslamHaourn** [comment]
I tried:
# Train phase: get loss
                if is_training:
                    x, *losses = module[0](x, targets, img_size)
                    for name, loss in zip(self.loss_names, losses):
                        self.losses[name] += loss
                # Test phase: Get detections
                else:
                    x = module(x)
but gave the same error

**Comment by EslamHaourn** [comment]
I tried:
elif not self.darknet and module_def["type"] == "yolo":
                # Train phase: get loss
                if is_training:
                    x, *losses = module[0](x, targets, img_dim)
                    for name, loss in zip(self.loss_names, losses):
                        self.losses[name] += loss
                # Test phase: Get detections
                else:
                    x = module(x)
but gave the same error
